default: &default
  adapter: postgresql
  username: rails
  password: rails

development:
  <<: *default
  database: trello_github_hooks_dev
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: trello_github_hooks_test
  min_messages: warning

production:
  <<: *default
  database: trello_github_hooks_production
